name: lang_table
description: >-
  lang_table is a dart plugin to generate string files from a source. Use
  a table to manage all multi-language resources.

version: 0.2.0
homepage: https://github.com/vlaushkin/lang_table

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  ansicolor: ^2.0.3
  http: ^1.5.0
